---
- name: Create application directory
  file: path={{deploy_path}} state=directory recurse=yes
  become: yes

- name: Create log directory
  file: path={{logs_dir}} state=directory recurse=yes
  become: yes

- name: Stop service GDHI
  systemd:
    name: gdhi.service
    state: stopped
    daemon_reload: yes
  become: yes

- name: Remove existing jar
  file:
    path: "{{deploy_path}}/{{gdhi_jar}}"
    state: absent  

- name: Download GDHI_service artifact
  get_url:
    url: "{{artifact_service_url}}"
    dest: "{{deploy_path}}/{{gdhi_jar}}"
  become: yes

- name: GDHI appllication.yml copy template file
  template:
    src: application.yml.j2
    dest: "{{deploy_path}}/application.yml"
  become: yes


- name: GDHI service copy template file
  template:
    src: gdhi.service.j2
    dest: /etc/systemd/system/gdhi.service
  become: yes


- name: Start service GDHI
  systemd:
    name: gdhi.service
    state: restarted
    daemon_reload: yes
  become: yes
