---
- name: Create application directory
  file: path={{deploy_path}} state=directory recurse=yes
  become: yes

- name: Create log directory
  file: path={{logs_dir}} state=directory recurse=yes
  become: yes

- name: Check that the gdhi.service exists
  stat:
    path: /etc/systemd/system/gdhi.service
  register: stat_result
  tags: production

- name: Stop service GDHI
  systemd:
    name: gdhi.service
    state: stopped
    daemon_reload: yes
  become: yes
  when: stat_result.stat.exists == True
  tags: production

- name: Check that the gdhi exists
  stat:
    path: /etc/init.d/gdhi
  register: stat_showcase_result
  tags: showcase

- name: Stop service GDHI showcase
  service:
    name: gdhi
    state: stopped
  become: yes
  when: stat_showcase_result.stat.exists == True
  tags: showcase

- name: Remove existing jar
  file:
    path: "{{deploy_path}}/{{gdhi_jar}}"
    state: absent  
  become: yes  

- name: Download GDHI_service artifact
  get_url:
    url: "{{artifact_service_url}}"
    dest: "{{deploy_path}}/{{gdhi_jar}}"
  become: yes

- name: GDHI appllication.yml copy template file
  template:
    src: application.yml.j2
    dest: "{{deploy_path}}/application.yml"
  become: yes


- name: GDHI service copy template file
  template:
    src: gdhi.service.j2
    dest: /etc/systemd/system/gdhi.service
  become: yes
  tags: production


- name: Start service GDHI
  systemd:
    name: gdhi.service
    state: restarted
    daemon_reload: yes
  become: yes
  tags: production

- name: GDHI service copy template file for showcase
  template:
    src: gdhi.j2
    dest: /etc/init.d/gdhi
  become: yes
  tags: showcase


- name: Start service GDHI showcase
  service:
    name: gdhi
    state: restarted
  become: yes
  tags: showcase
