---
  - name: production service tasks
    include: production.yml
    tags: production

  - name: qa service tasks
    include: qa.yml
    tags: qa

  - name: showcase_v2 service tasks
    include: showcase_v2.yml
    tags: showcase_v2
