---
- name: Download GDHI_service artifact
  get_url:
    url: "{{artifact_service_url}}"
    dest: "{{deploy_path}}/{{gdhi_jar}}"
  become: yes

- name: GDHI appllication.yml copy template file
  template:
    src: application.yml.j2
    dest: /opt/gdhi/service
  become: yes

- name: GDHI service copy template file
  template:
    src: gdhi.service.j2
    dest: /etc/systemd/system/gdhi.service
  become: yes

- name: Start service GDHI
  systemd:
    name: gdhi.service
    state: restarted
    daemon_reload: yes
  become: yes
