---
- name: Create application directory
  file: path={{deploy_path}} state=directory recurse=yes
  become: yes

- name: Create log directory
  file: path={{logs_dir}} state=directory recurse=yes
  become: yes

- name: Check that the gdhi.service exists
  stat:
    path: /etc/systemd/system/gdhi.service
  register: stat_result

- name: Stop service GDHI
  systemd:
    name: gdhi.service
    state: stopped
    daemon_reload: yes
  become: yes
  when: stat_result.stat.exists == True

- name: Find existing jar
  find:
    paths: "{{deploy_path}}"
    patterns: "gdhi-1.0.*"
  register: jar_files
  become: yes

- name: Remove existing jar
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ jar_files['files'] }}"
  become: yes

- name: Download GDHI_service artifact
  get_url:
    url: "{{artifact_service_url}}"
    dest: "{{deploy_path}}/{{gdhi_jar}}"
  become: yes

- name: GDHI appllication.yml copy template file
  template:
    src: application.yml.j2
    dest: "{{deploy_path}}/application.yml"
  become: yes

- name: GDHI logback.yml copy template file
  template:
    src: logback-spring.xml.j2
    dest: "{{deploy_path}}/logback-spring.xml"
  become: yes

- name: GDHI service copy template file
  template:
    src: gdhi.service.j2
    dest: /etc/systemd/system/gdhi.service
  become: yes

- name: Start service GDHI
  systemd:
    name: gdhi.service
    state: restarted
    daemon_reload: yes
  become: yes
