---
- name: Create application directory
  file: path={{deploy_path}} state=directory recurse=yes
  become: yes

- name: Create log directory
  file: path={{logs_dir}} state=directory recurse=yes
  become: yes

- name: Check that the gdhi.service exists
  stat:
    path: /etc/systemd/system/gdhi.service
  register: stat_result

- name: Stop service GDHI
  systemd:
    name: gdhi.service
    state: stopped
    daemon_reload: yes
  become: yes
  when: stat_result.stat.exists == True

# - name: Check that the gdhi exists
#   stat:
#     path: /etc/init.d/gdhi
#   register: stat_showcase_result
#
# - name: Stop service GDHI showcase
#   service:
#     name: gdhi
#     state: stopped
#   become: yes
#   when: stat_showcase_result.stat.exists == True

- name: Find existing jar
  find:
    paths: "{{deploy_path}}"
    patterns: "gdhi-1.0.*"
  register: jar_files

- name: Remove existing jar
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ jar_files['files'] }}"
  become: yes

- name: Get GDHI Service Build Number
  uri: url="{{ service_build_number_url }}" return_content=yes
  register: service_build_number

- name: Print Service Build Number
  debug:
    msg: "Service Build Number: {{ service_build_number }}"

- name: Construct GDHI tar file name
  set_fact:
    gdhi_jar: gdhi-1.0.{{ service_build_number.content }}.jar

- name: Construct Artifact service url
  set_fact:
    artifact_service_url: "http://ec2-34-206-29-117.compute-1.amazonaws.com:8080/job/gdhi-service/{{ service_build_number.content }}/artifact/build/libs/{{gdhi_jar}}"

- name: Download GDHI_service artifact
  get_url:
    url: "{{artifact_service_url}}"
    dest: "{{deploy_path}}/{{gdhi_jar}}"
  become: yes

- name: GDHI appllication.yml copy template file
  template:
    src: application.yml.j2
    dest: "{{deploy_path}}/application.yml"
  become: yes

- name: GDHI logback.yml copy template file
  template:
    src: logback-spring.xml.j2
    dest: "{{deploy_path}}/logback-spring.xml"
  become: yes

- name: GDHI service copy template file
  template:
    src: gdhi.service.j2
    dest: /etc/systemd/system/gdhi.service
  become: yes

- name: Start service GDHI
  systemd:
    name: gdhi.service
    state: restarted
    daemon_reload: yes
  become: yes

# - name: GDHI service copy template file for showcase
#   template:
#     src: gdhi.j2
#     dest: /etc/init.d/gdhi
#   become: yes

# - name: Start service GDHI showcase
#   service:
#     name: gdhi
#     state: restarted
#   become: yes
