---
  - name: install apache web server
    yum:
       name: httpd
       state: present
    become: yes

  - name: production apache tasks
    include: production.yml
    tags: production

  - name: showcase apache tasks
    include: showcase.yml
    tags: showcase

  - name: qa apache tasks
    include: qa.yml
    tags: qa

  - name: showcase_v2 apache tasks
    include: showcase_v2.yml
    tags: showcase_v2
