---
  - name: install apache web server
    yum:
       name: httpd
       state: present
    become: yes

  - name: production tasks
    include: production.yml

  - name: showcase tasks
    include: showcase.yml

