---
  - name: install apache web server
    yum:
       name: httpd
       state: present
    become: yes

  - name: production tasks
    include: production.yml
    tags: production

  - name: showcase tasks
    include: showcase.yml
    tags: showcase

  - name: qa tasks
    include: qa.yml
    tags: qa
