---
  - name: install apache web server
    yum:
       name: httpd
       state: present
    become: yes

  - name: Web Service Config file
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    become: yes

  - name: Install libsemanage package
    yum: name=libsemanage-python state=present
  

  - name: Selinux Httpd Can Connect
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
    become: yes

  - name: Daemon_Reload HTTPD
    systemd:
      name: httpd
      state: restarted
      daemon_reload: yes
    become: yes
