---

- name: Selinux Httpd Can Connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: yes
  tags: production

- name: Daemon_Reload HTTPD
  systemd:
    name: httpd
    state: restarted
    daemon_reload: yes
  become: yes
  tags: production
