---
# - name: Selinux Httpd Can Connect
#   seboolean:
#     name: httpd_can_network_connect
#     state: yes
#     persistent: yes
#   become: yes

- name: Installing passlib module
  yum:
      name: python-passlib
      state: present

- name: Setting admin authentication details
  htpasswd:
    path: /etc/users
    name: "{{ admin_username }}"
    password: "{{ admin_password }}"
    owner: root
    mode: 0640

- name: Web Service Config file
  template:
    src: httpd_qa.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  become: yes

- name: Daemon_Reload HTTPD
  systemd:
    name: httpd
    state: restarted
    daemon_reload: yes
  become: yes
