---
  - name: Download GDHI_App Artifact
    unarchive:
      src: "{{ artifact_app_url }}"
      dest: "{{deploy_dir}}"
      remote_src: yes
      mode: 0777
      extra_opts: [--strip-components=1]
    become: yes
    tags: showcase_v2

  - name: Get GDHI App Build Number
    uri: url="{{ app_build_number_url }}" return_content=yes
    register: app_build_number
    tags: qa

  - name: Construct GDHI tar file name
    set_fact:
      gdhi_tar: gdhi-1.0.{{ app_build_number }}.tar.gz
    tags: qa

  - name: Construct Artifact app url
    set_fact:
      artifact_app_url: "http://ec2-34-206-29-117.compute-1.amazonaws.com:8080/job/gdhi-app/{{ app_build_number }}/artifact/{{gdhi_tar}}"
    tags: qa

  - name: Download GDHI_App Artifact
    unarchive:
      src: "{{ artifact_app_url }}"
      dest: "{{deploy_dir}}"
      remote_src: yes
      mode: 0777
      extra_opts: [--strip-components=1]
    become: yes
    tags: qa

  - name: Download GDHI_App Artifact
    unarchive:
      src: "{{ artifact_app_url }}"
      dest: "{{deploy_dir}}"
      remote_src: yes
      mode: 0777
      extra_opts: [--strip-components=1]
    become: yes
    tags: production
