---
  - name: production app tasks
    include: production.yml
    tags: production

  - name: qa app tasks
    include: qa.yml
    tags: qa

  - name: showcase_v2 app tasks
    include: showcase_v2.yml
    tags: showcase_v2
