---
# tasks file for service
- name: Download GDHI_Service Artifact
  get_url:
    url: "{{Artifact_App_Url}}"
    dest: /var/www/html
    timeout: 30
  become: yes

- name: Daemon_Reload GDHI
  systemd:
    name: gdhi.service
    state: stopped
    daemon_reload: yes
  become: yes

- name: GDHI Service Copy Template file
  template:
    src: gdhi.service
    dest: /etc/systemd/system/gdhi.service
  become: yes

- name: Daemon_Reload GDHI
  systemd:
    name: gdhi.service
    state: started
    daemon_reload: yes
  become: yes

- name: Start Service GDHI
  systemd:
    name: gdhi.service
    state: restarted
  become: yes
